CI: Integrate macOS/arm64
Specify using gcc-14 instead of gcc (which typically points to the
latest version of gcc) due to a macOS limitation in the
rlalik/setup-cpp-compiler@master action. According to [1], each gcc must
have specified version.

Softfloat build warning error using gcc-14 with optimization flag O1:
In file included from src/softfloat/source/include/internals.h:42,
                 from src/softfloat/source/s_mulAddF64.c:40:
In function 'softfloat_sub128',
    inlined from 'softfloat_mulAddF64' at
src/softfloat/source/s_mulAddF64.c:185:17:
src/softfloat/source/include/primitives.h:526:17: error: 'sig128C.v64'
may be used uninitialized [-Werror=maybe-uninitialized]
  526 |     z.v64 = a64 - b64;
      |             ~~~~^~~~~
src/softfloat/source/s_mulAddF64.c: In function 'softfloat_mulAddF64':
src/softfloat/source/s_mulAddF64.c:66:20: note: 'sig128C.v64' was
declared here
   66 |     struct uint128 sig128C;
      |                    ^~~~~~~
In function 'softfloat_sub128',
    inlined from 'softfloat_mulAddF64' at
src/softfloat/source/s_mulAddF64.c:185:17:
src/softfloat/source/include/primitives.h:527:18: error: 'sig128C.v0'
may be used uninitialized [-Werror=maybe-uninitialized]
  527 |     z.v64 -= (a0 < b0);
      |              ~~~~^~~~~
src/softfloat/source/s_mulAddF64.c: In function 'softfloat_mulAddF64':
src/softfloat/source/s_mulAddF64.c:66:20: note: 'sig128C.v0' was
declared here
   66 |     struct uint128 sig128C;
Add -Wno-initialized to surpress them.

Drop the undefined behavior test on macOS/arm64 using gcc-14, as its
libsanitizer's configure.txt does not yet support it, check [2].

[1] https://github.com/rlalik/setup-cpp-compiler
[2] https://github.com/iains/gcc-darwin-arm64/blob/master-wip-apple-si/
    libsanitizer/configure.tgt

Close #519